---
title: "Índice de Progresso Social"
subtitle: "Uma análise dos indicadores de construção do índice de progresso social"
output: html_notebook
---

# Análise Descritiva de Dados

#### Importando Pacotes

```{r}
require(dplyr)
require(GGally)
library(ggplot2)
library(reshape2)
library(caret)

```

#### Importando Bases

```{r}
ips_componentes = read.csv(file = "https://raw.githubusercontent.com/Claudionor20/MultivariateAnalysis/main/bases/ips_componentes1620.csv")
ips_componentes = ips_componentes[,-1]

ips_indicadores = read.csv(file = "https://raw.githubusercontent.com/Claudionor20/MultivariateAnalysis/main/bases/ips_indicadores1620.csv")
ips_indicadores = ips_indicadores[,-1]

```

#### Left Join

```{r}
ips <- ips_componentes|>
  dplyr::left_join(ips_indicadores, by = c("ano", "regiao_administrativa"))
```

## Plotando Gráficos

### Média de IPS ao longo dos anos por região administrativa

```{r}
ips |>
  group_by(regiao_administrativa) %>%
  summarise(media_ips = mean(ips_geral)) %>%
  arrange(desc(media_ips)) %>%
  ggplot(aes(x = reorder(regiao_administrativa, media_ips), y = media_ips)) +
  geom_bar(stat = "identity", fill = "blue") +
  theme_minimal() +
  coord_flip() +
  labs(title = "Média de IPS por Região Administrativa",
       x = "Região Administrativa",
       y = "Média de IPS")

```

### Evolução anual do IPS de cada regisão administrativa

```{r fig.width=15, fig.height=8}
ips |>
  ggplot(aes(x = factor(ano), y = ips_geral)) +
  geom_bar(stat = "identity", position = "dodge", aes(fill = regiao_administrativa), width = 0.7) +
  scale_fill_viridis_d() +  
  theme_minimal() +
  theme(
    text = element_text(size = 14),  
    axis.text.x = element_text(size = 12),  
    axis.text.y = element_text(size = 12),  
    legend.title = element_text(size = 12), 
    legend.text = element_text(size = 10),  
    panel.grid.major = element_line(color = "gray", linetype = "dotted"),  
    panel.grid.minor = element_blank()  
  ) +
  labs(
    title = "Evolução do IPS por Região Administrativa",
    x = "Ano",
    y = "IPS",
    fill = "Região Administrativa"
  ) +
  facet_wrap(~ regiao_administrativa, scales = "free_y", ncol = 6)  
```

### Boxplot dos indicadores de IPS por ano

```{r}
ips_geral <- ips|>
  select(ano,ips_geral)

ips_geral|>
  ggplot(aes(x = as.factor(ano), y = ips_geral)) +
  geom_boxplot(aes(fill = "Ano"), color = "gray50", outlier.color = "red", outlier.shape = 16, outlier.size = 3) +
  scale_fill_manual(values = "#66C2A5") + 
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.major.x = element_blank(),  
    panel.grid.minor = element_blank(),  
    legend.position = "none"  
  ) +
  labs(
    title = "Distribuição do IPS por Ano",
    x = "Ano",
    y = "IPS"
  )
```
### Histogramas

```{r fig.width=12, fig.height=8}
data_long <- melt(ips, id.vars = c("ano", "regiao_administrativa"))


ggplot(data_long, aes(x = value)) +
  geom_histogram(bins = 30, fill = "blue", alpha = 0.7) +
  theme_minimal() +
  facet_wrap(~ variable, scales = "free_x") +
  labs(title = "Histogramas Dos Indicadores do IPS",
       x = "Valor",
       y = "Frequência")
```

### Análise de Correlação

##### Matriz de Correlação

```{r fig.width=12, fig.height=8}
correlacao <- cor(ips[,-c(1,2)])
corrplot(correlacao, method = "circle", tl.cex = 0.6)
```

##### Variáveis de alta correlação com IPS

```{r}
correlacao_ips <- as.data.frame(correlacao)
correlacao_ips <- correlacao_ips[1,]

variaveis_correlacionadas_ips <- which(correlacao_ips > 0.7)
nomes_variaveis_correlacionadas_ips <- colnames(correlacao_ips)[variaveis_correlacionadas_ips]
print(nomes_variaveis_correlacionadas_ips)

# É possível perceber que a maioria dos indicadores de IPS possuem correlação alta com o próprio IPS

```
